### ISSUE TITLE
Tomcat and CIMDraw

### ISSUE THREAD

**Issue by miha1111** [danielePala/CIMDraw#6]
hy,

is it possible to start CIMDraw on Tomcat server? If yes than I need WAR file to run CIMDraw on it.

Best regards,
Miha

**Comment by danielePala** [comment]
Hello, I don't have much experience with Tomcat, however since CIMDraw is a completely static web application, it should be quite easy to serve it.
For example, you can just follow the solution described [here](https://www.moreofless.co.uk/static-content-web-pages-images-tomcat-outside-war/).
